= SpacecraftAPI
:author: Xavier Quiñones
:rouge-style: github
:!showtitle:
:icons: font
:toc: preamble

== Description

Sandbox REST API with the following features:

* Pagination
* CRUD w/ persistence (H2 or PostgreSQL)
* Unit and Integration Testing
* Aspects
* Complete Exception Handling
* Caching (w/ Caffeine)
* Dockerization
* Security with Spring Security. JWT (Including Refresh Token) and User Roles
* Swagger (http://localhost:8080/swagger-ui/index.html)
* Lombok
* Testing dataset on startup

== Run the application

=== Clone the repository

----
git clone https://github.com/xaviqo/spacecraft-api.git
----

=== Run with Docker

* *Requirements:*

** Docker (https://docs.docker.com/get-started/)
** Compose (https://docs.docker.com/compose/install/)

* Move to *Docker* folder from terminal:

----
cd Docker/
----

* Build

----
docker-compose build --no-cache
----

* Launch

----
docker-compose up
----

=== Or build and run locally

* *Requirements:*

** Java 21 JRE && SDK

* In the *pom.xml* file _(root API folder)_ comment the *Postgres* dependency and uncomment the *H2* one.

* In the *application.yml* file _(resources folder)_ comment the JDBC *Postgres* connexion and uncomment the *H2* one.

* Then, move to *SpacecraftAPI* folder from terminal:

----
cd SpacecraftAPI/
----

* Launch:

** Run tests:

----
./mvnw test
----

** Start API:

----
./mvnw spring-boot:run
----

====
*In local execution* _(not available with docker and PgDB)_, you can access the embedded GUI console of H2DB from the following URL:

* http://localhost:8080/h2-console
====

== REST Endpoints
=== White listed

* *Get all spacecrafts (with pagination)* [GET] _Optional Params: (page && size)_: /v1/api/spacecraft

* *Get spacecraft by id* [GET]: /v1/api/spacecraft/{_id_} (_This method response is cached for 10 seconds_)

* *Get spacecraft if spacecraft name contains param*  [GET] _Params: (name)_: /v1/api/spacecraft/search

* *Create new user with role USER* [POST]: /v1/api/account/sign-up

.Request body example
[source,json]
----
{
  "username":"hola",
  "password":"adios"
}
----

* *Sign In* [POST]: /v1/api/account/sign-in

.Request body example
[source,json]
----
{
  "username":"hola",
  "password":"adios"
}
----

=== Secured _(Bearer token required)_
==== USER and ADMIN role

* *Create new spacecraft* [POST]: /v1/api/spacecraft

.Request body example
[source,json]
----
{
    "name": "Sputnik 2",
    "maxSpeed": 1957,
    "width": 2000,
    "height": 4000,
    "crewSize": 1,
    "status": "DESTROYED"
  }
----

* *Update specified spacecraft fields*  [POST]: /v1/api/spacecraft/{_id_}

.Request body example
[source,json]
----
{
    "name": "Nebuchadnezzar",
    "maxSpeed": 1337,
    "status": "UNDER_REPAIR"
  }
----

* *Refresh access token*  [POST]: /v1/api/account/refresh

==== Only ADMIN role

* *Delete spacecraft* [DELETE]: /v1/api/spacecraft/{_id_}

== Static

* SWAGGER UI: http://localhost:8080/swagger-ui/index.html

* H2 GUI _(not available w/ Docker)_: http://localhost:8080/h2-console

== Configuration parameters

* These are the configuration parameters available in the application.yaml file:

[source,yaml]
----
xavi:
  tech:
    spacecraft:
      cfg:
        test:
          fake-spacecraft-entries: Number of fake spacecraft entries (int)
          credentials:
            create-fake-accounts: Create fake accounts (bool)
            admin: Admin creds separted by coma (str [admin,pwd])
            user: User creds separated by coma (str [user,pwd])
        jwt:
          issuer: JWT token issuer (str)
          access-tkn-exp-sec: Access token expiration time in sec (int)
          refresh-tkn-exp-sec: Refresh token expiration time in sec (int)

logging:
  level:
    tech.xavi.spacecraft: Log level for our own code (TRACE,DEBUG,INFO...)
    root: Log level from application root (TRACE,DEBUG,INFO...)

spring:
  datasource:
    url: JDBC URI for datasource (str)
    username: Datasource username (str)
    password: Datasource password (str)
  jpa:
    hibernate:
      ddl-auto: Schema manipulation on app startup (create-drop,update...)
  h2:
    console:
      enabled: Enable H2 UI (bool)
springdoc:
  api-docs:
    path: Springdoc path (str)
----