xavi:
  tech:
    spacecraft:
      cfg:
        test:
          fake-spacecraft-entries: 100
          credentials:
            create-fake-accounts: true
            admin: admin,admin
            user: user,user
        jwt:
          issuer: spacecraft-api
          access-tkn-exp-sec: 120
          refresh-tkn-exp-sec: 320


logging:
  level:
    tech.xavi.spacecraft: DEBUG
    root: INFO

spring:
  datasource:
    url: jdbc:h2:mem:spacecraftdb
#    url: ${SC_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spacecraftapi?currentSchema=public&ssl=false}
    username: ${SC_DATASOURCE_USER:sc}
    password: ${SC_DATASOURCE_PASS:pwd}
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
springdoc:
  api-docs:
    path: /openapi

server:
  port: 8080