xavi:
  tech:
    spacecraft:
      cfg:
        fake-entries: 40

logging:
  level:
    tech.xavi.spacecraft: DEBUG

spring:
  datasource:
#    url: jdbc:h2:mem:spacecraftdb
#    driver-class-name: org.h2.Driver
    url: ${SC_DATASOURCE_URL:jdbc:postgresql://localhost:5432/spacecraftapi?currentSchema=public&ssl=false}
    username: ${SC_DATASOURCE_USER:sc}
    password: ${SC_DATASOURCE_PASS:pwd}
  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
springdoc:
  api-docs:
    path: /openapi