xavi:
  tech:
    spacecraft:
      cfg:
        fake-entries: 40

logging:
  level:
    tech.xavi.spacecraft: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:spacecraftdb
    driver-class-name: org.h2.Driver
    username: sc
    password: pwd
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
springdoc:
  api-docs:
    path: /openapi